In [1]:
import numpy as np
np.__version__

'1.26.4'

In [112]:
a=np.array([1,2,3,5,7,8])
a[0],type(a)

(1, numpy.ndarray)

In [6]:
a2=np.array([4,5,7,8])

In [7]:
id(a),id(a2)

(2127856097520, 2127893438000)

In [8]:
a3=a #since the array is copied it will be having same id
print(id(a3))

2127856097520


In [11]:
d=np.array({"a":1,"b":2})

In [13]:
type(d),d

(numpy.ndarray, array({'a': 1, 'b': 2}, dtype=object))

In [28]:
l=[i for i in range(10)]
b=np.arange(10)
[i for i in np.arange(1,10,2)]

[1, 3, 5, 7, 9]

In [29]:
len(l)
b.size

10

In [32]:
np.array([1,3.0,'hi'])

array(['1', '3.0', 'hi'], dtype='<U32')

In [33]:
np.array(['apple','banana','mango'])

array(['apple', 'banana', 'mango'], dtype='<U6')

In [113]:
a=np.linspace(1,10)
a,len(a)

(array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
         1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
         2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
         3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
         4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
         5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
         6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
         7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
         8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
         9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ]),
 50)

In [42]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [43]:
np.zeros(10),np.ones(10)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [155]:
li=[[1,2,3],[4,5,6],[7,8,9]]
li[0][0]

AttributeError: 'list' object has no attribute 'dim'

In [116]:
arr=np.array(li)
arr.ndim

2

In [117]:
li=[[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]
a=np.array(li)
a.ndim,a.shape

(3, (2, 2, 3))

In [58]:
np.zeros((2,3)),np.zeros((2,3),dtype=int)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[0, 0, 0],
        [0, 0, 0]]))

In [158]:
a=np.array([1,2,3,4,5,6,7,8,9])
a.reshape((3,3)),a.reshape((3,-1))

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [139]:
data=np.random.randn(2,3)
data,np.mean(data)

(array([[-1.0856306 ,  0.99734545,  0.2829785 ],
        [-1.50629471, -0.57860025,  1.65143654]]),
 -0.039794181242410076)

In [138]:
s=0
for i in range(0,2):
    for j in range(0,3):
        s=s+data[i][j]
print(s/6)        

0.25343525957539464


In [67]:
%time for i in range(1000):np.arange(1000000)*2

CPU times: total: 7.23 s
Wall time: 10.1 s


In [74]:
%time for i in range(1000):list(range(10000))*2

CPU times: total: 281 ms
Wall time: 716 ms


In [162]:
a=np.array([1,2,3,4,5,6])
a=np.append(a,7)
a


array([1, 2, 3, 4, 5, 6, 7])

In [91]:
a=np.array([[1,2],[3,4]])
a=np.append(a,[[5,6]],axis=0)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [93]:
a=np.append(a,[[7],[8],[9]],axis=1)
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [96]:
np.delete(a,0,axis=1),np.delete(a,0,axis=0)

(array([[2, 7],
        [4, 8],
        [6, 9]]),
 array([[3, 4, 8],
        [5, 6, 9]]))

In [97]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [100]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b,a-b,a*b,a/b


(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0.25, 0.4 , 0.5 ]))

In [101]:
print(a.ndim)
print(a.size)
print(a.shape)


1
3
(3,)


In [106]:
b=[1,2,3]
3*b,np.tile(a,3),3*a,np.repeat(a,3)

([1, 2, 3, 1, 2, 3, 1, 2, 3],
 array([1, 2, 3, 1, 2, 3, 1, 2, 3]),
 array([3, 6, 9]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3]))

In [120]:
c=np.arange(9)
c=c.reshape(3,3)
np.tile(c,2),c**2

(array([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]]),
 array([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]]))

In [121]:
a=np.array([1,2,3,4])
a%2==0

array([False,  True, False,  True])

In [127]:
a**3,np.sqrt(a),np.power(a,0.5)

(array([ 1,  8, 27, 64], dtype=int32),
 array([1.        , 1.41421356, 1.73205081, 2.        ]),
 array([1.        , 1.41421356, 1.73205081, 2.        ]))

In [130]:
x=np.arange(1,11)
x.sum(),x.mean(),x.var(),x.std(),x.cumsum()

(55,
 5.5,
 8.25,
 2.8722813232690143,
 array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55]))

In [133]:
x.reshape(2,-1),x.reshape(5,-1)

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]))

In [164]:
x=x.reshape(2,-1)
a=np.array([1,2,3])
np.mean(x,axis=0),x.mean(axis=0),a.mean(axis=0),np.unique(x),np.round(8.2),np.floor(8.2),np.ceil(8.2),np.trunc(8.2),np.max(x),np.min(x)

(array([3.5, 4.5, 5.5, 6.5, 7.5]),
 array([3.5, 4.5, 5.5, 6.5, 7.5]),
 2.0,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 8.0,
 8.0,
 9.0,
 8.0,
 10,
 1)

In [160]:
np.random.seed(123),np.random.randint(1,11,3)

(None, array([3, 3, 7]))