In [3]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([3,2,0,1]).reshape(2,2)
a,b

(array([[1, 2],
        [3, 4]]),
 array([[3, 2],
        [0, 1]]))

In [4]:
a.dot(b),np.dot(a,b)

(array([[ 3,  4],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 9, 10]]))

In [7]:
np.transpose(a),a.transpose()

(array([[1, 3],
        [2, 4]]),
 array([[1, 3],
        [2, 4]]))

In [10]:
np.linalg.inv(a),np.linalg.det(a)

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 -2.0000000000000004)

In [11]:
a=np.array([0,1,2,3])
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [12]:
b[0],b[0][1]

(array([0, 1, 2, 3]), 1)

In [14]:
a=np.arange(10,100,10).reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
a[2][2]

90

In [17]:
a[2,2]=0
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80,  0]])

In [18]:
a[1][1]=0
a

array([[10, 20, 30],
       [40,  0, 60],
       [70, 80,  0]])

In [19]:
a[2]=np.array([1,2,3])
a

array([[10, 20, 30],
       [40,  0, 60],
       [ 1,  2,  3]])

In [21]:
a[[0,2],[0,1]]

array([10,  2])

In [22]:
a[a>3]

array([10, 20, 30, 40, 60])

In [23]:
a[a%2==0]

array([10, 20, 30, 40,  0, 60,  2])

In [30]:
a=np.empty((8,4))

In [32]:
for i in range(8):
    a[i]=i
a    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [33]:
a[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [34]:
a[[-3,-5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [36]:
a2=np.arange(20)
amask=(a2%5==0)
a2[amask],amask

(array([ 0,  5, 10, 15]),
 array([ True, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False,  True, False, False,
        False, False]))

In [37]:
amask2=(a2>10)
a2[amask & amask2]

array([15])

In [39]:
arr=np.arange(0,15).reshape(3,5)
arr.transpose(),arr.T

(array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [41]:
arr=np.random.randn(6,3)
arr.T

array([[-2.90294088, -0.64011886, -1.28564653, -1.28994733, -0.00303614,
        -0.4253335 ],
       [ 0.33210606,  0.71515501,  0.61930297, -0.90251017,  0.5143502 ,
         0.82390678],
       [-0.62892918,  0.09858715, -0.40158422,  1.04247576,  1.01220942,
         0.34985579]])

In [45]:
np.dot(arr.T,arr)

array([[12.33458681, -1.40587939,  0.78231467],
       [-1.40587939,  2.76318041, -0.51903469],
       [ 0.78231467, -0.51903469,  2.80026391]])

In [47]:
a1=np.arange(12).reshape(3,4)
a1.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
a1.transpose((0,1)),a1.transpose((1,0))

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [56]:
a1.swapaxes(0,1),a1.swapaxes(1,0)

(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))