In [1]:
import tensorflow as tf


In [ ]:
!pip install tensorflow

In [2]:
scalar=tf.constant(7)
scalar

scalar.ndim

vector=tf.constant([10,10])
vector

vector.ndim

matrix=tf.constant([[1,2,3],[1,2,3]])
matrix

matrix.ndim

matrix1=tf.constant([[1,2,3],[1,2,3],[1,2,3]],dtype=tf.float16)
matrix1

matrix1.ndim

tensor=tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

tensor

tensor.ndim

3

In [3]:
changeable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changeable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [4]:
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)

In [ ]:
unchangable_tensor[0].assign(7)

In [ ]:
random1=tf.random.Generator.from_seed(42)
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))
random1,random2,random1==random2

In [5]:
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [6]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [7]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [8]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [9]:
import numpy as np
arr=np.arange(1,25,dtype=np.int32)

In [10]:
Tens=tf.constant(arr,shape=(6,4))

In [11]:
Tens

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [12]:
Tens[0]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [13]:
tf.size(Tens)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [14]:
rank4tensor=tf.zeros(shape=(2,3,4,5))
rank4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [16]:
rank4tensor.shape #rank is nothing but the shape

TensorShape([2, 3, 4, 5])

In [17]:
tf.size(rank4tensor),tf.size(rank4tensor).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=120>, np.int32(120))

In [18]:
rank4tensor.ndim

4

In [19]:
rank4tensor.dtype

tf.float32

In [20]:
rank4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [21]:
rank4tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank4tensor[:1,:1,:4,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [23]:
rank2tensor=tf.constant([[1,2],[3,4]])
rank2tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
rank2tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [25]:
rank3tensor=rank2tensor[...,tf.newaxis]

In [26]:
rank3tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [28]:
tf.expand_dims(rank2tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [29]:
tf.expand_dims(rank2tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [30]:
tf.expand_dims(rank2tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [33]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [35]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
t2=tf.constant([[1,2],[3,4]])
tf.linalg.matmul(tensor,t2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 48],
       [15, 22]], dtype=int32)>

In [37]:
t1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2=tf.constant([[3,5],[6,7],[1,8]])
tf.linalg.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [38]:
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [47]:
t=tf.constant([[1,2,3],[4,5,6]])
t,tf.reshape(t,shape=(3,2)),tf.transpose(t)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [42]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [44]:
t1,t2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [46]:
tf.tensordot(t1,t2,axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
when axis dont line up its better to use transpose than reshape

In [ ]:
aggregation functions

In [48]:
b=tf.constant([1.7,7.4])
b.dtype

tf.float32

In [49]:
c=tf.constant([1,2])
c.dtype

tf.int32

In [52]:
b=tf.cast(b,dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [53]:
d=tf.constant([-7,-1])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -1], dtype=int32)>

In [55]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 1], dtype=int32)>

In [56]:
import numpy as np
rand=tf.constant(np.random.randint(0,100,size=50))
rand

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([13,  0, 38, 66, 76, 94, 39, 21, 41, 41, 88, 29, 86, 62,  4, 16, 71,
       80, 64, 67, 97, 71, 67, 21, 72, 18, 23, 65,  6, 50, 68, 20,  3, 23,
       94, 64, 38, 82, 22, 33, 54, 46, 12, 69, 26, 71, 15, 53, 41, 97],
      dtype=int32)>

In [57]:
tf.reduce_min(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [58]:
tf.reduce_max(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [59]:
tf.reduce_mean(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [60]:
tf.reduce_sum(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=2417>

In [70]:
import tensorflow_probability as tfp
tfp.stats.variance(rand)

<tf.Tensor: shape=(), dtype=int32, numpy=787>

In [67]:
!pip install tensorflow_probability

   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   --- ------------------------------------ 0.5/7.0 MB 2.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/7.0 MB 2.4 MB/s eta 0:00:03
   --------- ------------------------------ 1.6/7.0 MB 2.8 MB/s eta 0:00:02
   ------------- -------------------------- 2.4/7.0 MB 2.7 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.0 MB 2.7 MB/s eta 0:00:02
   ------------------- -------------------- 3.4/7.0 MB 2.7 MB/s eta 0:00:02
   ---------------------- ----------------- 3.9/7.0 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 4.5/7.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------- ----------- 5.0/7.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 6.3/7.0 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  6.8/7.0 MB 2.7 MB/s eta 0:00:01
   ----------------

In [69]:
!pip install tf_keras

   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 3.4 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 2.8 MB/s eta 0:00:00


In [77]:
tf.math.reduce_std(tf.cast(rand,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.064645767211914>

In [76]:
tf.math.reduce_variance(tf.cast(rand,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=787.6243896484375>

In [ ]:
positional maxi andd mini

In [83]:
tf.random.set_seed(42)
tens=tf.random.uniform(shape=[50])
tens

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [86]:
tf.argmax(tens),tens[tf.argmax(tens)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

In [88]:
tf.argmin(tens),tens[tf.argmin(tens)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>)

In [89]:
tens[tf.argmax(tens)]==tf.reduce_max(tens)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
squeezing a tensor

In [92]:
tf.random.set_seed(42)
tens2=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
tens2                 

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [93]:
tens2.shape

TensorShape([1, 1, 1, 1, 50])

In [94]:
tens2_sqe=tf.squeeze(tens2)
tens2_sqe

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
tens2_sqe.shape

TensorShape([50])

In [98]:
l=[0,1,2,3,4]
tf.one_hot(l,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [100]:
tf.one_hot(l,depth=5,on_value='yes',off_value='no')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'no', b'yes']], dtype=object)>

In [101]:
t=tf.range(1,10)
t

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [102]:
tf.square(t)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [107]:
tf.sqrt(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [111]:
tf.math.log(tf.cast(t,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
tensors and numpy
tf and np can interact very well

In [112]:
tens2=tf.constant(np.array([3.,7.,10.]))
tens2

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [113]:
np.array(tens2)

array([ 3.,  7., 10.])

In [115]:
tens2.numpy()

array([ 3.,  7., 10.])

In [117]:
nptens=tf.constant(np.array([3.,7.]))
tftens=tf.constant([3.,7.])
nptens.dtype,tftens.dtype

(tf.float64, tf.float32)

In [120]:
tf.config.list_physical_devices("GPU")

[]